[book]
title = "PowerShell FAQ"
author = "PoshCode Community"
description = "Frequently Asked Questions in the PowerShell Community"
language = "en"
src = "src"

[build]
build-dir = "docs"
create-missing = false

[preprocessor.index]

[preprocessor.links]

[output.html]
mathjax-support = true
site-url = "/"
git-repository-url = "https://github.com/PoshCode/PowerShellFAQ"


[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[rust]
edition = "2018"